import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/* 폰트는 나중에 보자! */
//const geistSans = Geist({
//  variable: "--font-geist-sans",
//  subsets: ["latin"],
//});

//const geistMono = Geist_Mono({
//  variable: "--font-geist-mono",
//  subsets: ["latin"],
//});

//export const metadata: Metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};

// props에 밑줄은 ts 작성하지 않아서 나오는 것. 일단 무시
export default function RootLayout(props) {
  return (
    <html lang="en">
      <body>
        <div>======여기는 레이아웃 입니다=====</div>
        {props.children}
        <div>======여기는 레이아웃 입니다=====</div>
      </body>
    </html>
  );
}

/* 
    [ Next 실행 순서 ]
    1.  주소창에 주소 입력
        => http://localhost3000/

    2.  입력된 주소의 폴더안의 page.tsx 찾기
        => app/page.tsx
        (ex. 주소: /mypage는? => app/mypage/page.tsx 찾기)
        해당 구조는 next.js 프레임워크는 이미 react Route 기능이 내장되어 있기 떄문에 가능!

    3. 해당 페이지컴포넌트 통째로 props에 넣어서 실행하기
    <RootLayout children={해당페이지 컴포넌트} />
*/